### PR TITLE
Several metadata enhancements

### LINKED ISSUE #21: Favicon sizes
We should support multiple favicon sizes b/c of different screen densities and platforms.

how to: http://www.w3schools.com/tags/att_link_sizes.asp
One reason why: http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android

### PR DESCRIPTION
**Pull request by MariusVolkhart**
- High-res favicon for Chrome on Lollipop
- App banner for Safari on iOS
- Meta data to pin on Windows 8 and Firefox mobile

Fixes #21 

@atscott @maconsuckow please review. I didn't build b/c the instructions didn't work.

- [x] Does the Windows stuff work?
- [x] Chrome seems to be broken but all indicators are that we're doing it right and it's a chrome bug. Other sites don't work either.
- [x] Favicon works for retina screens
- [ ] Favicon works for non-retina screens

### CODE REVIEW

**Comment by atscott** [comment]
Gonna need more than "instructions didn't work." It's important to me that they are up to date and it's easy to get up-and-running with the code.

**Comment by atscott** [comment]
Windows stuff works alright. Icon is there and IE styles to the website colors. Kind of looks a little bit like Japan's flag. Can we make the pin icon look more like Google's? See screenshot below:
screen shot 2015-03-29 at 8 00 50 am

This also might be a good time to discuss again if we like either of the favicons Katlyn drew up. These might look better as pinned icons:
icon1
icon2

**Comment by MariusVolkhart** [comment]
Do a cache refresh. I update the favicon and added high res versions so
pinning on windows shouldn't look like shit. Its the circle with the white
TM in it now

**Comment by atscott** [comment]
Right you are. Looking good. 
screen shot 2015-03-29 at 1 43 05 pm

**Comment by atscott** [comment]
[:thumbsup:]

**Pull request merged**
